return {
  -- {
  --   "zbirenbaum/copilot.nvim",
  --   event = { "BufEnter" },
  --   config = function()
  --     require("copilot").setup({
  --       suggestion = {
  --         enabled = false,
  --       },
  --       panel = { enabled = false },
  --     })
  --   end,
  -- },
  -- {
  --   "zbirenbaum/copilot-cmp",
  --   event = { "BufEnter" },
  --   dependencies = { "zbirenbaum/copilot.nvim" },
  --   config = function()
  --     require("copilot-cmp").setup()
  --   end,
  -- },
}
